global:
    track: 0
    marker: 0

out:
    - csv
    - osc://localhost:8000

aliases: 
    - &defaultScalarFunction |
        function() {
            if (Math.abs((value/127.0) - parseFloat(data.value)) < 0.1) {
                return value;
            }
            
            return false;
        }

in:
    nanoKONTROL2*:
        -   key: 0
            name: fader00
            type: scalar
            shape: *defaultScalarFunction
            map: [0, 1]
            value: 0.5

        -   key: 1
            name: fader01
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 2
            name: fader02
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 3
            name: fader03
            type: scalar
            map: [0, 1]
            value: 0
        
        -   key: 4
            name: fader04
            type: scalar
            map: [0, 1]
            value: 0
    
        -   key: 5
            name: fader05
            type: scalar
            map: [0, 1]
            value: 0
        
        -   key: 6
            name: fader06
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 7
            name: fader07
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 16
            name: knob00
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 17
            name: knob01
            type: scalar
            map: [0, 1]
        
        -   key: 18
            name: knob02
            type: scalar
            map: [0, 1]
        
        -   key: 19
            name: knob03
            type: scalar
            map: [0, 1]
        
        -   key: 20
            name: knob04
            type: scalar
            map: [0, 1]
        
        -   key: 21
            name: knob05
            type: scalar
            map: [0, 1]
        
        -   key: 22
            name: knob06
            type: scalar
            map: [0, 1]
        
        -   key: 23
            name: knob07
            type: scalar
            map: [0, 1]
        
        -   key: 32
            name: sBtns0
            type: toggle
            value: false
        
        -   key: 33
            name: sBtns1
            type: toggle
            value: off
        
        -   key: 34
            name: sBtns2
            type: toggle
            value: off
        
        -   key: 35
            name: sBtns3
            type: toggle
            value: off

        -   key: 36
            name: sBtns4
            type: toggle
            value: off

        -   key: 37
            name: sBtns5
            type: toggle
            value: off
        
        -   key: 38
            name: sBtns6
            type: toggle
            value: off
        
        -   key: 39
            name: sBtns7
            type: toggle
            value: off
        
        -   key: 41
            name: play
            type: toggle
            value: false
        
        -   key: 42
            name: stop
            type: button
        
        -   key: 43
            name: backward
            type: button
        
        -   key: 44
            name: forward
            type: button

        -   key: 45
            name: rec
            type: toggle

        -   key: 46
            name: cycle
            type: button

        -   key: 48
            name: mBtns0
            type: toggle
            value: false
        
        -   key: 49
            name: mBtns1
            type: toggle
            value: off

        -   key: 50
            name: mBtns2
            type: toggle
            value: off
        
        -   key: 51
            name: mBtns3
            type: toggle
            value: off
        
        -   key: 52
            name: mBtns4
            type: toggle
            value: off
        
        -   key: 53
            name: mBtns5
            type: toggle
            value: off
        
        -   key: 54
            name: mBtns6
            type: toggle
            value: off
        
        -   key: 55
            name: mBtns7
            type: toggle
            value: off

        -   key: 58
            name: track_back
            type: scalar
            shape: |
                function() {
                    if (global.track == 0)
                        return false;

                    if (value == 127)
                        return global.track--;
                    
                    return false;
                }

        -   key: 59
            name: track_fwd
            type: scalar
            shape: |
                function() {
                    if (value == 127)
                        return ++global.track;
                    
                    return false;
                }

        -   key: 60
            name: marker_set
            type: toggle

        -   key: 61
            name: marker_fwd
            type: scalar
            shape: |
                function() {
                    if (global.marker == 0)
                        return false;

                    if (value == 127)
                        return --global.marker;
                    
                    return false;
                }

        -   key: 62
            name: marker_fwd
            type: scalar
            shape: |
                function() {
                    if (value == 127)
                        return global.marker++;
                    
                    return false;
                }

        -   key: 64
            name: rBtns0
            type: toggle
            value: false

        -   key: 65
            name: rBtns1
            type: toggle
            value: off
        
        -   key: 66
            name: rBtns2
            type: toggle
            value: off
        
        -   key: 67
            name: rBtns3
            type: toggle
            value: off
        
        -   key: 68
            name: rBtns4
            type: toggle
            value: off
        
        -   key: 69
            name: rBtns5
            type: toggle
            value: off

        -   key: 70
            name: rBtns6
            type: toggle
            value: off

        -   key: 71
            name: rBtns7
            type: toggle
            value: off