global:
    track: 0
    marker: 0
    timer: false
    time: 0
    time_dir: 0.1

out:
    - csv
    - osc://localhost:8000

aliases: 
    - &defaultScalarFunction |
            function() {
                if (Math.abs(value - parseFloat(data.value_raw)) < 5.0) {
                    return value;
                }
                return false;
            }

pulse:
    -   name: main
        interval: 100
        type: scalar
        shape: |
            function() {
                if (global.timer) {
                    global.time = parseFloat(global.time) + global.time_dir
                    return global.time;
                }
                else
                    return false;
            }


in:
    nanoKONTROL2*:
        -   key: 0
            name: fader00
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0.5

        -   key: 1
            name: fader01
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 2
            name: fader02
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 3
            name: fader03
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0
        
        -   key: 4
            name: fader04
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0
    
        -   key: 5
            name: fader05
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0
        
        -   key: 6
            name: fader06
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 7
            name: fader07
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 16
            name: knob00
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
            value: 0

        -   key: 17
            name: knob01
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 18
            name: knob02
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 19
            name: knob03
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 20
            name: knob04
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 21
            name: knob05
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 22
            name: knob06
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 23
            name: knob07
            shape: *defaultScalarFunction
            type: scalar
            map: [0, 1]
        
        -   key: 32
            name: sBtns0
            type: toggle
            value: false
        
        -   key: 33
            name: sBtns1
            type: toggle
            value: off
        
        -   key: 34
            name: sBtns2
            type: toggle
            value: off
        
        -   key: 35
            name: sBtns3
            type: toggle
            value: off

        -   key: 36
            name: sBtns4
            type: toggle
            value: off

        -   key: 37
            name: sBtns5
            type: toggle
            value: off
        
        -   key: 38
            name: sBtns6
            type: toggle
            value: off
        
        -   key: 39
            name: sBtns7
            type: toggle
            value: off
        
        -   key: 41
            name: play
            type: toggle
            shape: |
                function() {
                    if (data.value)
                        global.timer = true;
                    else
                        global.timer = false;

                    return value;
                }
            value: false
        
        -   key: 42
            name: stop
            type: button
        
        -   key: 43
            name: backward
            type: button
            shape: |
                function() {
                    if (value == 127)
                        global.time_dir -= 0.01;

                    return false;
                }

        -   key: 44
            name: forward
            type: button
            shape: |
                function() {
                    if (value == 127)
                        global.time_dir += 0.01;

                    return false;
                }

        -   key: 45
            name: rec
            type: toggle

        -   key: 46
            name: cycle
            type: button

        -   key: 48
            name: mBtns0
            type: toggle
            value: false
        
        -   key: 49
            name: mBtns1
            type: toggle
            value: off

        -   key: 50
            name: mBtns2
            type: toggle
            value: off
        
        -   key: 51
            name: mBtns3
            type: toggle
            value: off
        
        -   key: 52
            name: mBtns4
            type: toggle
            value: off
        
        -   key: 53
            name: mBtns5
            type: toggle
            value: off
        
        -   key: 54
            name: mBtns6
            type: toggle
            value: off
        
        -   key: 55
            name: mBtns7
            type: toggle
            value: off

        -   key: 58
            name: track_back
            type: scalar
            shape: |
                function() {
                    if (global.track == 0)
                        return false;

                    if (value == 127)
                        return --global.track;
                    
                    return false;
                }

        -   key: 59
            name: track_fwd
            type: scalar
            shape: |
                function() {
                    if (value == 127)
                        return ++global.track;
                    
                    return false;
                }

        -   key: 60
            name: marker_set
            type: toggle

        -   key: 61
            name: marker_fwd
            type: scalar
            shape: |
                function() {
                    if (global.marker == 0)
                        return false;

                    if (value == 127)
                        return --global.marker;
                    
                    return false;
                }

        -   key: 62
            name: marker_fwd
            type: scalar
            shape: |
                function() {
                    if (value == 127)
                        return global.marker++;
                    
                    return false;
                }

        -   key: 64
            name: rBtns0
            type: toggle
            value: false

        -   key: 65
            name: rBtns1
            type: toggle
            value: off
        
        -   key: 66
            name: rBtns2
            type: toggle
            value: off
        
        -   key: 67
            name: rBtns3
            type: toggle
            value: off
        
        -   key: 68
            name: rBtns4
            type: toggle
            value: off
        
        -   key: 69
            name: rBtns5
            type: toggle
            value: off

        -   key: 70
            name: rBtns6
            type: toggle
            value: off

        -   key: 71
            name: rBtns7
            type: toggle
            value: off