nanoKONTROL2_20_0:

    out:
        osc:
            address: localhost
            port: 8000

        csv: on

    events:
        -   name: fader00
            type: scalar
            map: [0, 1]

        -   name: fader01
            type: lerp
            map: [0, 50, 150, 250, 255, 0]

        -   name: fader02
            type: states
            map: [low, med, high, ultra_high]

        -   name: fader03
            type: scalar
            map: [0, 1]

        -   name: fader04
            type: scalar
            map: [0, 1]

        -   name: fader05
            type: scalar
            map: [0, 1]

        -   name: fader06
            type: scalar
            map: [0, 1]

        -   name: fader07
            type: scalar
            map: [0, 1]

        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none

        -   name: knob00
            type: scalar
            map: [0, 1]

        -   name: knob01
            type: scalar
            map: [0, 1]

        -   name: knob02
            type: scalar
            map: [0, 1]

        -   name: knob03
            type: scalar
            map: [0, 1]

        -   name: knob04
            type: scalar
            map: [0, 1]

        -   name: knob05
            type: scalar
            map: [0, 1]

        -   name: knob06
            type: scalar
            map: [0, 1]

        -   name: knob07
            type: scalar
            map: [0, 1]
            
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none

        -   name: sBtns0
            type: switch
            value: off

        -   name: sBtns1
            type: switch
            value: off
            map:
                on: define,TEST
                off: undefine,TEST

        -   name: sBtns2
            type: switch
            value: off

        -   name: sBtns3
            type: switch
            value: off

        -   name: sBtns4
            type: switch
            value: off

        -   name: sBtns5
            type: switch
            value: off

        -   name: sBtns6
            type: switch
            value: off

        -   name: sBtns7
            type: switch
            value: off

        -   type: none

        -   name: play
            type: button

        -   name: stop
            type: button

        -   name: backward
            type: button

        -   name: forward
            type: button

        -   name: rec
            type: button

        -   name: cycle
            type: button

        -   type: none

        -   name: mBtns0
            type: switch
            value: off

        -   name: mBtns1
            type: switch
            value: off

        -   name: mBtns2
            type: switch
            value: off

        -   name: mBtns3
            type: switch
            value: off

        -   name: mBtns4
            type: switch
            value: off

        -   name: mBtns5
            type: switch
            value: off

        -   name: mBtns6
            type: switch
            value: off

        -   name: mBtns7
            type: switch
            value: off
            
        -   type: none
        -   type: none

        -   name: trackPrev
            type: button

        -   name: trackNext
            type: button

        -   name: markerSet
            type: switch

        -   name: markerPrev
            type: button

        -   name: markerNext
            type: button
            
        -   type: none

        -   name: rBtns0
            type: switch
            value: off

        -   name: rBtns1
            type: switch
            value: off

        -   name: rBtns2
            type: switch
            value: off

        -   name: rBtns3
            type: switch
            value: off

        -   name: rBtns4
            type: switch
            value: off

        -   name: rBtns5
            type: switch
            value: off

        -   name: rBtns6
            type: switch
            value: off

        -   name: rBtns7
            type: switch
            value: off

        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none
        -   type: none


    