global:
    time: 13.0
    string: test
    question: true
    
out:
    -   osc://localhost:8000
in:
    nanoKONTROL2*:
        0:
            name: fader00
            type: scalar
            value: 0
            out:
                -   osc://localhost:8000
                -   csv
        1:
            name: fader01
            type: scalar
            value: 0
        2:
            name: fader02
            type: scalar
            value: 0
        3:
            name: fader03
            type: scalar
            value: 0
        4:
            name: fader04
            type: scalar
            value: 0
        5:
            name: fader05
            type: scalar
            value: 0
        6:
            name: fader06
            type: states
            value: 0
        7:
            name: fader07
            type: scalar
            value: 0
        16:
            name: knob00
            type: scalar
            value: 0
        17:
            name: knob01
            type: scalar
        18:
            name: knob02
            type: scalar
        19:
            name: knob03
            type: scalar
        20:
            name: knob04
            type: scalar
        21:
            name: knob05
            type: scalar
        22:
            name: knob06
            type: scalar
        23:
            name: knob07
            type: scalar
        32:
            name: sBtns0
            type: toggle
            value: false
        33:
            name: sBtns1
            type: toggle
            value: off
        34:
            name: sBtns2
            type: toggle
            value: off
        35:
            name: sBtns3
            type: toggle
            value: off
        36:
            name: sBtns4
            type: toggle
            value: off
        37:
            name: sBtns5
            type: toggle
            value: off
        38:
            name: sBtns6
            type: toggle
            value: off
        39:
            name: sBtns7
            type: toggle
            value: off
        41:
            name: play
            type: toggle
            value: false
        42:
            name: stop
            type: button
        43:
            name: backward
            type: button
        44:
            name: forward
            type: button
        45:
            name: rec
            type: toggle
        46:
            name: cycle
            type: button
        48:
            name: mBtns0
            type: toggle
            value: false
        49:
            name: mBtns1
            type: toggle
            value: off
        50:
            name: mBtns2
            type: toggle
            value: off
        51:
            name: mBtns3
            type: toggle
            value: off
        52:
            name: mBtns4
            type: toggle
            value: off
        53:
            name: mBtns5
            type: toggle
            value: off
        54:
            name: mBtns6
            type: toggle
            value: off
        55:
            name: mBtns7
            type: toggle
            value: off
        64:
            name: rBtns0
            type: toggle
            value: false
        65:
            name: rBtns1
            type: toggle
            value: off
        66:
            name: rBtns2
            type: toggle
            value: off
        67:
            name: rBtns3
            type: toggle
            value: off
        68:
            name: rBtns4
            type: toggle
            value: off
        69:
            name: rBtns5
            type: toggle
            value: off
        70:
            name: rBtns6
            type: toggle
            value: off
        71:
            name: rBtns7
            type: toggle
            value: off