nanoKONTROL2_20_0:

    out:
        osc:
            address: localhost
            port: 8000
            folder: /u/

        csv:
            pre: u_

    events:
        -   name: fader00
            range: [0, 1]
        -   name: fader01
            range: [0, 1]
        -   name: fader02
            range: [0, 1]
        -   name: fader03
            range: [0, 1]
        -   name: fader04
            range: [0, 1]
        -   name: fader05
            range: [0, 1]
        -   name: fader06
            range: [0, 1]
        -   name: fader07
            range: [0, 1]

        -   name: v08
        -   name: v09
        -   name: v10
        -   name: v11
        -   name: v12
        -   name: v13
        -   name: v14
        -   name: v15

        -   name: knob00
            range: [0, 1]
        -   name: knob01
            range: [0, 1]
        -   name: knob02
            range: [0, 1]
        -   name: knob03
            range: [0, 1]
        -   name: knob04
            range: [0, 1]
        -   name: knob05
            range: [0, 1]
        -   name: knob06
            range: [0, 1]
        -   name: knob07
            range: [0, 1]

        -   name: v24
        -   name: v25
        -   name: v26
        -   name: v27
        -   name: v28
        -   name: v29
        -   name: v30
        -   name: v31

        -   name: sBtns0
            toggle: on
        -   name: sBtns1
            toggle: off
        -   name: sBtns2
            toggle: off
        -   name: sBtns3
            toggle: off
        -   name: sBtns4
            toggle: off
        -   name: sBtns5
            toggle: off
        -   name: sBtns6
            toggle: off
        -   name: sBtns7
            toggle: off

        -   name: v40
        -   name: play
        -   name: stop
        -   name: backward
        -   name: forward
        -   name: rec
        -   name: cycle
        -   name: v47

        -   name: mBtns0
            toggle: off
        -   name: mBtns1
            toggle: off
        -   name: mBtns2
            toggle: off
        -   name: mBtns3
            toggle: off
        -   name: mBtns4
            toggle: off
        -   name: mBtns5
            toggle: off
        -   name: mBtns6
            toggle: off
        -   name: mBtns7
            toggle: off

        -   name: v56
        -   name: v57
        -   name: trackPrev
        -   name: trackNext
        -   name: markerSet
        -   name: markerPrev
        -   name: markerNext
        -   name: v63

        -   name: rBtns0
            toggle: off
        -   name: rBtns1
            toggle: off
        -   name: rBtns2
            toggle: off
        -   name: rBtns3
            toggle: off
        -   name: rBtns4
            toggle: off
        -   name: rBtns5
            toggle: off
        -   name: rBtns6
            toggle: off
        -   name: rBtns7
            toggle: off

        -   name: v72
        -   name: v73
        -   name: v74
        -   name: v75
        -   name: v76
        -   name: v77
        -   name: v78
        -   name: v79


    